//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class FirClient_Component_CLuaAnimatorWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(FirClient.Component.CLuaAnimator), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("Initialize", new LuaCSFunction(Initialize));
		L.RegFunction("Play", new LuaCSFunction(Play));
		L.RegFunction("Dispose", new LuaCSFunction(Dispose));
		L.RegFunction("__eq", new LuaCSFunction(op_Equality));
		L.RegFunction("__tostring", new LuaCSFunction(ToLua.op_ToString));
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Initialize(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			FirClient.Component.CLuaAnimator obj = (FirClient.Component.CLuaAnimator)ToLua.CheckObject<FirClient.Component.CLuaAnimator>(L, 1);
			LuaTable arg0 = ToLua.CheckLuaTable(L, 2);
			LuaFunction arg1 = ToLua.CheckLuaFunction(L, 3);
			obj.Initialize(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Play(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			FirClient.Component.CLuaAnimator obj = (FirClient.Component.CLuaAnimator)ToLua.CheckObject<FirClient.Component.CLuaAnimator>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.Play(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Dispose(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			FirClient.Component.CLuaAnimator obj = (FirClient.Component.CLuaAnimator)ToLua.CheckObject<FirClient.Component.CLuaAnimator>(L, 1);
			obj.Dispose();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

