//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class FirClient_Define_EventNamesWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(FirClient.Define.EventNames), typeof(System.Object));
		L.RegFunction("New", _CreateFirClient_Define_EventNames);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("EvLogicUpdate", get_EvLogicUpdate, null);
		L.RegVar("EvNpcSpawn", get_EvNpcSpawn, null);
		L.RegVar("EvNpcSpawnOK", get_EvNpcSpawnOK, null);
		L.RegVar("EvEnterScene", get_EvEnterScene, null);
		L.RegVar("EvBeginPlay", get_EvBeginPlay, null);
		L.RegVar("EvMoveCamera", get_EvMoveCamera, null);
		L.RegVar("EvNpcSkillAttack", get_EvNpcSkillAttack, null);
		L.RegVar("EvNpcSkillAttackOK", get_EvNpcSkillAttackOK, null);
		L.RegVar("EvNpcDeath", get_EvNpcDeath, null);
		L.RegVar("EvEnterDungeon", get_EvEnterDungeon, null);
		L.RegVar("EvEnterDungeonOK", get_EvEnterDungeonOK, null);
		L.RegVar("EvBattleStart", get_EvBattleStart, null);
		L.RegVar("EvBattleEnd", get_EvBattleEnd, null);
		L.RegVar("EvChooseNpc", get_EvChooseNpc, null);
		L.RegVar("EvNpcMove", get_EvNpcMove, null);
		L.RegVar("EvNpcMoveOK", get_EvNpcMoveOK, null);
		L.RegVar("EvNpcFaceDir", get_EvNpcFaceDir, null);
		L.RegVar("EvNpcShow", get_EvNpcShow, null);
		L.RegVar("EvNpcShowOK", get_EvNpcShowOK, null);
		L.RegVar("EvShowDialog", get_EvShowDialog, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateFirClient_Define_EventNames(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				FirClient.Define.EventNames obj = new FirClient.Define.EventNames();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: FirClient.Define.EventNames.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EvLogicUpdate(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, FirClient.Define.EventNames.EvLogicUpdate);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EvNpcSpawn(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, FirClient.Define.EventNames.EvNpcSpawn);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EvNpcSpawnOK(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, FirClient.Define.EventNames.EvNpcSpawnOK);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EvEnterScene(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, FirClient.Define.EventNames.EvEnterScene);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EvBeginPlay(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, FirClient.Define.EventNames.EvBeginPlay);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EvMoveCamera(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, FirClient.Define.EventNames.EvMoveCamera);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EvNpcSkillAttack(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, FirClient.Define.EventNames.EvNpcSkillAttack);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EvNpcSkillAttackOK(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, FirClient.Define.EventNames.EvNpcSkillAttackOK);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EvNpcDeath(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, FirClient.Define.EventNames.EvNpcDeath);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EvEnterDungeon(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, FirClient.Define.EventNames.EvEnterDungeon);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EvEnterDungeonOK(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, FirClient.Define.EventNames.EvEnterDungeonOK);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EvBattleStart(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, FirClient.Define.EventNames.EvBattleStart);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EvBattleEnd(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, FirClient.Define.EventNames.EvBattleEnd);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EvChooseNpc(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, FirClient.Define.EventNames.EvChooseNpc);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EvNpcMove(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, FirClient.Define.EventNames.EvNpcMove);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EvNpcMoveOK(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, FirClient.Define.EventNames.EvNpcMoveOK);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EvNpcFaceDir(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, FirClient.Define.EventNames.EvNpcFaceDir);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EvNpcShow(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, FirClient.Define.EventNames.EvNpcShow);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EvNpcShowOK(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, FirClient.Define.EventNames.EvNpcShowOK);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EvShowDialog(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, FirClient.Define.EventNames.EvShowDialog);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

