// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package com.protos;

public interface AddressBookOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pb_common.AddressBook)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .pb_common.Person people = 1;</code>
   */
  java.util.List<com.protos.Person> 
      getPeopleList();
  /**
   * <code>repeated .pb_common.Person people = 1;</code>
   */
  com.protos.Person getPeople(int index);
  /**
   * <code>repeated .pb_common.Person people = 1;</code>
   */
  int getPeopleCount();
  /**
   * <code>repeated .pb_common.Person people = 1;</code>
   */
  java.util.List<? extends com.protos.PersonOrBuilder> 
      getPeopleOrBuilderList();
  /**
   * <code>repeated .pb_common.Person people = 1;</code>
   */
  com.protos.PersonOrBuilder getPeopleOrBuilder(
      int index);
}
