// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pbuser.proto

package com.protos;

public final class pbuser {
  private pbuser() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_user_ReqLogin_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_user_ReqLogin_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_user_ResLogin_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_user_ResLogin_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014pbuser.proto\022\007pb_user\032\014common.proto\"&\n" +
      "\010ReqLogin\022\014\n\004name\030\001 \001(\t\022\014\n\004pass\030\002 \001(\t\"X\n" +
      "\010ResLogin\022%\n\006result\030\001 \001(\0162\025.pb_common.Re" +
      "sultCode\022%\n\010userinfo\030\002 \001(\0132\023.pb_common.U" +
      "serInfoB\'\n\ncom.protosB\006pbuserP\001\252\002\016Networ" +
      "k.pbuserb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.protos.pb_common.getDescriptor(),
        }, assigner);
    internal_static_pb_user_ReqLogin_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pb_user_ReqLogin_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_user_ReqLogin_descriptor,
        new java.lang.String[] { "Name", "Pass", });
    internal_static_pb_user_ResLogin_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_pb_user_ResLogin_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_user_ResLogin_descriptor,
        new java.lang.String[] { "Result", "Userinfo", });
    com.protos.pb_common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
